### ISSUE TITLE
Output into json

### ISSUE THREAD

**Issue by wrenix** [jrhawley/hb#1]
The rust debug format is not really machine readable ...

---
PS: you will safe my ash with your project - homebank export in csv and qif is not usable (it lost destination of transaction)

**Comment by jrhawley** [comment]
Hey @wrenix, thanks for submitting this. I've moved development of hb over to GitLab (https://gitlab.com/jrhawley/hb), so I should probably make archive this repo and redirect anyone who comes across it.

I'm actively working on this feature right now, but there are some tricky aspects to it.
XML parsing isn't trivial for XHB files, and I'm trying to a) find the right Rust crate to handling the parsing, or b) direct my efforts on serializing the data structures I already have in place.
Both of them have their pros and cons, but neither of them is trivial right now.

Ideally, I could get serialization working, which would make exporting to JSON pretty straightforward, and I'd also get exporting to other formats relatively easily.

**Comment by wrenix** [comment]
Please Announce your move to gitlab in your README or in your github Description (e.g replace it with your link to: https://jrhawley.ca/2022/04/14/homebank-cli)

Yes the serde library should work really easy on a print-output
